coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50%
        informational: true
    patch:
      default:
        target: auto
        threshold: 50%
        informational: true

# do not include tests folders
ignore:
  - "broadcast"
  - "transport/protocols/websockets"
  - "internal"
  - "tests"
  - "metrics/config_test.go"
  - "websockets/storage/storage_test.go"
  - "websockets/config.go"
  - "amqp/amqpjobs/config.go"
  - "beanstalk/config.go"
  - "redis/config.go"
  - "redis/kv/config.go"