coverage:
  status:
    project:
      default:
        target: auto
        threshold: 50%
        informational: true
    patch:
      default:
        target: auto
        threshold: 50%
        informational: true

# do not include tests folders
ignore:
  - ".github"
  - "api"
  - "config/configs"
  - "grpc/parser/parse_test.go"
  - "grpc/codec/codec_test.go"
  - "http/config"
  - "http/middleware/new_relic/error_test.go"
  - "http/middleware/new_relic/splitter_test.go"
  - "http/middleware/websockets/origin_test.go"
  - "jobs/pipeline/pipeline_test.go"
  - "jobs/job/job_test.go"
  - "metrics/config_test.go"
  - "tests"
  - "utils"
