version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  on_init:
    command: "any php or script here"
    exec_timeout: 20s
    env:
      - SOME_KEY: "SOME_VALUE"
      - SOME_KEY2: "SOME_VALUE2"
  command: "php psr-worker.php"
  user: ""
  group: ""
  env:
    - SOME_KEY: "SOME_VALUE"
    - SOME_KEY2: "SOME_VALUE2"

  relay: pipes
  relay_timeout: 60s

jobs:
  num_pollers: 32
  pipeline_size: 100000

  pool:
    num_workers: 10
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

  pipelines:
    test-local:
      driver: memory
      priority: 10

      config:
        prefetch: 10000

    test-local-1:
      driver: boltdb
      priority: 10

      config:
        file: "test-local-1-bolt.db"
        prefetch: 10000

    test-local-2:
      drier: amqp
      priority: 1

      config:
        prefetch: 10
        queue: test-1-queue
        exchange: default
        exchange_type: direct
        routing_key: test
        exclusive: false
        multiple_ack: false
        requeue_on_fail: false

    test-local-3:
      driver: beanstalk
      priority: 11

      config:
        tube_priority: 1
        tube: default-1
        reserve_timeout: 10s

    test-local-4:
      driver: sqs
      priority: 10
      prefetch: 10

      config:
        visibility_timeout: 0
        wait_time_seconds: 0
        queue: default

        attributes:
          DelaySeconds: 0
          MaximumMessageSize: 262144
          MessageRetentionPeriod: 345600
          ReceiveMessageWaitTimeSeconds: 0
          VisibilityTimeout: 30
        tags:
        test: "tag"

    test-local-5:
      driver: nats
      priority: 2
      prefetch: 100

      config:
        subject: default
        stream: foo
        deliver_new: true
        rate_limit: 100
        delete_stream_on_stop: false
        delete_after_ack: false

  consume:
    [
        "test-local",
        "test-local-1",
        "test-local-2",
        "test-local-3",
        "test-local-4",
        "test-local-5",
    ]

grpc:
  listen: "tcp://localhost:9001"
  proto:
    - "first.proto"
    - "second.proto"

  tls:
    key: ""
    cert: ""
    root_ca: ""
    client_auth_type: no_client_certs

  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s

  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60

tcp:
  servers:
    server1:
      addr: 127.0.0.1:7778
      delimiter: "\r\n"
      read_buf_size: 1
    server2:
      addr: 127.0.0.1:8811
      read_buf_size: 10
    server3:
      addr: 127.0.0.1:8812
      delimiter: "\r\n"
      read_buf_size: 1

  pool:
    num_workers: 5
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

fileserver:
  address: 127.0.0.1:10101
  calculate_etag: true
  weak: false
  stream_request_body: true

  serve:
    - prefix: "/foo"
      root: "../../../tests"
      compress: false
      cache_duration: 10
      max_age: 10
      bytes_range: true

    - prefix: "/foo/bar"
      root: "../../../tests"
      compress: false
      cache_duration: 10
      max_age: 10
      bytes_range: true

endure:
  grace_period: 30s
  print_graph: false
  log_level: error