server:
  command: "php tcp.php"
  user: ""
  group: ""
  env:
    "RR_CONFIG": "/some/place/on/the/C134"
    "RR_CONFIG2": "C138"
  relay: "tcp://localhost:9999"
  relayTimeout: "20s"
logs:
  mode: development
  level: error