name: build

on:
  push:
  pull_request:
    branches:
      # Branches from forks have the form 'user:branch-name' so we only run
      # this job on pull_request events for branches that look like fork
      # branches. Without this we would end up running this job twice for non
      # forked PRs, once for the push and then once for opening the PR.
      - '**:**'

jobs:
  golang:
    name: Build (Go ${{ matrix.go }}, PHP ${{ matrix.php }}, OS ${{matrix.os}})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0' ]
        go: [ '1.14', '1.15' ]
        os: [ ubuntu-20.04, windows-latest, macos-latest ]
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2 # action page: <https://github.com/actions/setup-go>
        with:
          go-version: ${{ matrix.go }}

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2 # action page: <https://github.com/shivammathur/setup-php>
        with:
          php-version: ${{ matrix.php }}
          extensions: sockets

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get Composer Cache Directory
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' }}
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Init Composer Cache # Docs: <https://git.io/JfAKn#php---composer>
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' }}
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: cd tests && composer update --prefer-dist --no-progress --ansi

      - name: Init Go modules Cache # Docs: <https://git.io/JfAKn#go---modules>
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download

      - name: Run golang tests on Windows without codecov
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          go test -v -race -cover -tags=debug ./a_plugin_tests/checker
          go test -v -race -cover -tags=debug ./a_plugin_tests/config
          go test -v -race -cover -tags=debug ./a_plugin_tests/gzip
          go test -v -race -cover -tags=debug ./a_plugin_tests/headers
          go test -v -race -cover -tags=debug ./a_plugin_tests/http
          go test -v -race -cover -tags=debug ./a_plugin_tests/informer
          go test -v -race -cover -tags=debug ./a_plugin_tests/logger
          go test -v -race -cover -tags=debug ./a_plugin_tests/metrics
          go test -v -race -cover -tags=debug ./a_plugin_tests/redis
          go test -v -race -cover -tags=debug ./a_plugin_tests/reload
          go test -v -race -cover -tags=debug ./a_plugin_tests/resetter
          go test -v -race -cover -tags=debug ./a_plugin_tests/rpc
          go test -v -race -cover -tags=debug ./a_plugin_tests/server
          go test -v -race -cover -tags=debug ./a_plugin_tests/static

      - name: Run golang tests on Linux and MacOS
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' }}
        run: |
          mkdir ./coverage-ci
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/checker.txt -covermode=atomic ./a_plugin_tests/checker
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/config.txt -covermode=atomic ./a_plugin_tests/config
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/gzip.txt -covermode=atomic ./a_plugin_tests/gzip
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/headers.txt -covermode=atomic ./a_plugin_tests/headers
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/http.txt -covermode=atomic ./a_plugin_tests/http
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/informer.txt -covermode=atomic ./a_plugin_tests/informer
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/logger.txt -covermode=atomic ./a_plugin_tests/logger
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/metrics.txt -covermode=atomic ./a_plugin_tests/metrics
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/redis.txt -covermode=atomic ./a_plugin_tests/redis
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/reload.txt -covermode=atomic ./a_plugin_tests/reload
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/resetter.txt -covermode=atomic ./a_plugin_tests/resetter
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/rpc.txt -covermode=atomic ./a_plugin_tests/rpc
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/server.txt -covermode=atomic ./a_plugin_tests/server
          go test -v -race -cover -tags=debug -coverprofile=./coverage-ci/static.txt -covermode=atomic ./a_plugin_tests/static
          cat ./coverage-ci/*.txt > ./coverage-ci/summary.txt

      - uses: codecov/codecov-action@v1 # Docs: <https://github.com/codecov/codecov-action>
        if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage-ci/summary.txt
          fail_ci_if_error: false

  golangci-lint:
    name: Golang-CI (lint)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run linter
        uses: golangci/golangci-lint-action@v2 # Action page: <https://github.com/golangci/golangci-lint-action>
        with:
          version: v1.33 # without patch version
          only-new-issues: false # show only new issues if it's a pull request

#   image:
#     name: Build docker image
#     runs-on: ubuntu-20.04
#     timeout-minutes: 10
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v2

#       - name: Build image
#         run: docker build -t roadrunner:local -f Dockerfile .

#       - name: Scan image
#         uses: anchore/scan-action@v2 # action page: <https://github.com/anchore/scan-action>
#         with:
#           image: roadrunner:local
#           fail-build: true
#           severity-cutoff: low # negligible, low, medium, high or critical
